clean up setup

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,40 +1,33 @@
 #!/bin/sh
 
-cd ~
+cd ~ || exit
 
-if [ ! -h .vimrc ]; then
-	ln -s ~/dotfiles/vimrc .vimrc
-	echo ".vimrc symlink created"
+files=(.vimrc .tmux.conf .zshrc .zshenv .pryrc .oh-my-zsh/themes/my.zsh-theme)
+mines=( vimrc  tmux.conf  zshrc  zshenv  pryrc  my.zsh-theme)
+files_length=${#files[@]}
+mines_length=${#mines[@]}
+
+if [ $files_length != $mines_length ]; then
+  printf "\nArrays 'files' and 'mines' do not match in length"
+  printf "\nEach 'file' requires a corresponding 'mine' version"
+  printf "\n\nCheck the arrays and re-run."
+  exit
 fi
 
-if [ ! -h .oh-my-zsh/themes/friskChuck.zsh-theme ]; then
-  ln -s ~/dotfiles/friskChuck.zsh-theme .oh-my-zsh/themes/friskChuck.zsh-theme
-	echo "friskChuck theme added"
-fi
+for ((i = 0; i < $files_length; i++)); do
+  if [ ! -h ${files[$i]} ]; then
+    echo "Not found: ${files[$i]}"
+    echo "Creating SYMLINK..."
+    ln -s ~/dotfiles/${mines[$i]} ${files[$i]}
+    if [ ! -h ${files[$i]} ]; then
+      echo "PANIC - unable to create SYMLINK"
+      echo "Failure while trying to create ${files[$i]}"
+      exit
+    fi
+    echo "Success!"
+  fi
+  echo "All set."
+done
 
-if [ ! -h .tmux.conf ]; then
-	ln -s ~/dotfiles/tmux.conf .tmux.conf
-	echo ".tmux.conf symlink created"
-fi
-
-if [ ! -h /usr/local/bin/tat ]; then
-	cd /usr/local/bin
-	ln -s ~/dotfiles/bin/tat tat
-	cd ~
-	echo "You now have the power of tat, courtesy of Upcase"
-fi
-
-if [ ! -h .zshrc ]; then
-	ln -s ~/dotfiles/zshrc .zshrc
-	echo "ZSHRC symlink created"
-fi
-
-if [ ! -h .zshenv ]; then
-	ln -s ~/dotfiles/zshenv .zshenv
-	echo "ZSHENV symlink created"
-fi
-
-if [ ! -h .pryrc ]; then
-	ln -s ~/dotfiles/pryrc .pryrc
-	echo "PryRC symlink created"
-fi
+cd ~/.oh-my-zsh/custom/plugins || exit
+git clone https://github.com/zsh-users/zsh-autosuggestions.git
